name: 'LEGO automerge'

on:
  pull_request:
    types:
      - opened
    branches:
      - Localization

permissions:
  contents: read

jobs:
  worker:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.actor == 'csigs'
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1 # v2.21.1
        with:
          egress-policy: audit

      - uses: actions/github-script@ffc2c79a5b2490bd33e0a41c1de74b877714d736 # v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: 'squash'
            })
